/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author wanderson
 */
public class JFrameCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCalculadora
     */
    public JFrameCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtClear = new javax.swing.JButton();
        jBtDiv = new javax.swing.JButton();
        jBt8 = new javax.swing.JButton();
        jBtMulti = new javax.swing.JButton();
        jBt5 = new javax.swing.JButton();
        jBtSubt = new javax.swing.JButton();
        jBtSoma = new javax.swing.JButton();
        jBt2 = new javax.swing.JButton();
        jBtRaiz = new javax.swing.JButton();
        jBt0 = new javax.swing.JButton();
        jBtIgual = new javax.swing.JButton();
        jBt9 = new javax.swing.JButton();
        jBt6 = new javax.swing.JButton();
        jBt7 = new javax.swing.JButton();
        jBt4 = new javax.swing.JButton();
        jBt3 = new javax.swing.JButton();
        jBt1 = new javax.swing.JButton();
        jBtPonto = new javax.swing.JButton();
        labelTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jBtClear.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBtClear.setText("C");

        jBtDiv.setText("/");
        jBtDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDivActionPerformed(evt);
            }
        });

        jBt8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt8.setText("8");

        jBtMulti.setText("X");

        jBt5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt5.setText("5");

        jBtSubt.setText("-");

        jBtSoma.setText("+");

        jBt2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt2.setText("2");
        jBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt2ActionPerformed(evt);
            }
        });

        jBtRaiz.setText("√");
        jBtRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRaizActionPerformed(evt);
            }
        });

        jBt0.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt0.setText("0");

        jBtIgual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtIgual.setText("=");

        jBt9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt9.setText("9");

        jBt6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt6.setText("6");

        jBt7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt7.setText("7");

        jBt4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt4.setText("4");

        jBt3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt3.setText("3");

        jBt1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBt1.setText("1");

        jBtPonto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBtPonto.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTela, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBt7)
                            .addComponent(jBt4)
                            .addComponent(jBt1)
                            .addComponent(jBtClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBt0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtPonto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBt3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBt8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBt9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBt5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBt6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtSoma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtMulti)
                                    .addComponent(jBtDiv)
                                    .addComponent(jBtSubt)
                                    .addComponent(jBtRaiz)))
                            .addComponent(jBtIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBt0, jBt1, jBt2, jBt3, jBt4, jBt5, jBt6, jBt7, jBt8, jBt9, jBtClear, jBtDiv, jBtMulti, jBtPonto, jBtSoma, jBtSubt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(labelTela, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtMulti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtDiv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtSubt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtRaiz))
                            .addComponent(jBtSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtIgual))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBt7)
                            .addComponent(jBt8)
                            .addComponent(jBt9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBt4)
                            .addComponent(jBt5)
                            .addComponent(jBt6))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBt1)
                            .addComponent(jBt2)
                            .addComponent(jBt3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtClear)
                            .addComponent(jBt0)
                            .addComponent(jBtPonto))))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRaizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtRaizActionPerformed

    private void jBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBt2ActionPerformed

    private void jBtDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt0;
    private javax.swing.JButton jBt1;
    private javax.swing.JButton jBt2;
    private javax.swing.JButton jBt3;
    private javax.swing.JButton jBt4;
    private javax.swing.JButton jBt5;
    private javax.swing.JButton jBt6;
    private javax.swing.JButton jBt7;
    private javax.swing.JButton jBt8;
    private javax.swing.JButton jBt9;
    private javax.swing.JButton jBtClear;
    private javax.swing.JButton jBtDiv;
    private javax.swing.JButton jBtIgual;
    private javax.swing.JButton jBtMulti;
    private javax.swing.JButton jBtPonto;
    private javax.swing.JButton jBtRaiz;
    private javax.swing.JButton jBtSoma;
    private javax.swing.JButton jBtSubt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTela;
    // End of variables declaration//GEN-END:variables
}
